version: 0.0
os: linux

resources:
  - name: devopsex4
    instanceType: t2.micro
    tags:
      - Key: Environment
        Value: Ex4

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 60
      runas: root
